# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ministry of Talent
email: Aga@Ministryoftalent.com
description: > # this means to ignore newlines until "baseurl:"
  "Blog o rozwoju, karierze i kulturze organizacji. U mnie dowiesz się co jest sourcing i poznasz dobre praktyki rekrutacyjne. Jeśli szukasz pracy pomogę w budowie CV i w przygotowaniu do rozmowy kwalifikacyjnej. Na łamach bloga dzielę się również doświadczeniem pracy w Londynie."
  
  
baseurl:
url: "http://ministryoftalent.co.uk" # the base hostname & protocol for your site

#sidebar
default-image: mono (1).png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: webjeda

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 9
paginate_path: /page:num/

# Tracker
analytics: UA-77735576-1  #changed for ministry

# Comments
disqus-shortname: Aga

#social
facebook: facebook.com/ministryoftalent
twitter: AgaDeszczka
linkedin:

#facebook like box
fb-app-id: 2015362445356281
fb-page-url: https://www.facebook.com/ministryoftalent
fb-page-title: Ministry of Talent

# Sass style
sass:
  style: compressed

# Ruby Gems

gems: [jekyll-paginate, jekyll-seo-tag]

